-- Sample data for public.beneficiarios
-- Run in the Supabase SQL editor after executing schema.sql

insert into public.beneficiarios (
  fecha,
  hora,
  caso_numero,
  forma_contacto,
  tipo_contacto,
  lugar_contacto,
  localidad,
  barrio,
  mismo_beneficiario,
  fuente_nombre,
  fuente_vinculo,
  fuente_telefono,
  nombre_apellido,
  fecha_nacimiento,
  genero,
  direccion,
  telefono,
  grupo_etnico,
  poblaciones_especiales,
  estado_civil,
  numero_hijos,
  convive_con,
  apoyo_social_personas,
  apoyo_social_interes,
  apoyo_social_vecinos,
  apoyo_social_puntaje,
  apoyo_social_nivel,
  escolaridad,
  usa_computador,
  ocupacion,
  alimentacion,
  practica_deporte,
  cual_deporte,
  participacion_comunitaria,
  ha_participado,
  situaciones_salud,
  situaciones_consumo,
  situaciones_entorno,
  situaciones_economicas,
  situaciones_legales,
  peticiones_apoyo,
  peticiones_necesidades,
  peticiones_capacitacion,
  peticiones_asesoria,
  descripcion_caso,
  nombre_diligencia,
  rol_diligencia,
  telefono_diligencia,
  emociones
) values
  (
    '2025-02-01',
    '09:15:00',
    1001,
    'en-persona',
    'primer-contacto',
    'casa',
    'Usme',
    'Barrio Nuevo',
    'si',
    null,
    null,
    null,
    'Maria Gomez',
    '1991-03-12',
    'Femenino',
    'Calle 12 #4-21',
    '3001112233',
    'Mestizo',
    ARRAY['victima-conflicto']::text[],
    'Union libre',
    '2',
    'Pareja e hijos',
    4,
    3,
    4,
    11,
    'Apoyo social moderado',
    'Tecnico',
    'si',
    'Comerciante',
    'regular',
    'si',
    'Zumba',
    'Junta de accion comunal',
    'si',
    ARRAY['hipertension']::text[],
    ARRAY['alcohol-ocasional']::text[],
    ARRAY['inseguridad-barrio']::text[],
    ARRAY['desempleo-reciente']::text[],
    ARRAY[]::text[],
    ARRAY['acompanamiento-psicosocial']::text[],
    ARRAY['mercados']::text[],
    ARRAY['emprendimiento']::text[],
    ARRAY['asesoria-juridica']::text[],
    'Busca fortalecimiento para negocio familiar.',
    'Laura Medina',
    'Psicologa',
    '3005551122',
    '[{"label":"Esperanza","intensity":0.7}]'::jsonb
  ),
  (
    '2025-02-02',
    '10:30:00',
    1002,
    'telefono',
    'seguimiento',
    'oficina',
    'Chapinero',
    'El Lago',
    'no',
    'Carlos Lopez',
    'Hermano',
    '3019998877',
    'Julio Ramirez',
    '1988-09-05',
    'Masculino',
    'Carrera 18 #82-11',
    '3204456677',
    'Afrodescendiente',
    ARRAY['discapacidad']::text[],
    'Soltero',
    '0',
    'Solo',
    2,
    2,
    2,
    6,
    'Bajo apoyo social',
    'Profesional',
    'si',
    'Diseñador grafico',
    'buena',
    'no',
    null,
    'Colectivo cultural',
    'si',
    ARRAY['diabetes-tipo2']::text[],
    ARRAY[]::text[],
    ARRAY['vivienda-en-arriendo']::text[],
    ARRAY['bajos-ingresos']::text[],
    ARRAY['proceso-legal-arrendador']::text[],
    ARRAY['apoyo-emocional']::text[],
    ARRAY['ayuda-alimentaria']::text[],
    ARRAY['capacitacion-digital']::text[],
    ARRAY[]::text[],
    'Requiere acompañamiento para proceso legal de vivienda.',
    'Andres Roa',
    'Abogado',
    '3021135790',
    '[{"label":"Ansiedad","intensity":0.6}]'::jsonb
  ),
  (
    '2025-02-03',
    '14:45:00',
    1003,
    'videollamada',
    'primer-contacto',
    'institucion',
    'Suba',
    'La Gaitana',
    'si',
    null,
    null,
    null,
    'Lucia Prieto',
    '1996-11-21',
    'Femenino',
    'Transversal 134 #110-09',
    '3058883322',
    'Indigena',
    ARRAY['mujer-cabeza-familia']::text[],
    'Casada',
    '3',
    'Pareja e hijos',
    5,
    5,
    4,
    14,
    'Alto apoyo social',
    'Secundaria',
    'no',
    'Artesana',
    'regular',
    'si',
    'Futbol',
    'Red de mujeres',
    'no',
    ARRAY['asma']::text[],
    ARRAY['tabaco-ocasional']::text[],
    ARRAY['saneamiento-deficiente']::text[],
    ARRAY['ingresos-inestables']::text[],
    ARRAY[]::text[],
    ARRAY['viveres']::text[],
    ARRAY['mejoramiento-vivienda']::text[],
    ARRAY['manualidades']::text[],
    ARRAY['asesoria-contable']::text[],
    'Quiere mejorar red de comercializacion artesanal.',
    'Paula Nieto',
    'Trabajadora social',
    '3122212345',
    '[{"label":"Alegria","intensity":0.5},{"label":"Incertidumbre","intensity":0.4}]'::jsonb
  ),
  (
    '2025-02-04',
    '08:20:00',
    1004,
    'en-persona',
    'seguimiento',
    'casa',
    'Bosa',
    'Porvenir',
    'no',
    'Marta Silva',
    'Vecina',
    '3114456778',
    'Pedro Ruiz',
    '1982-06-18',
    'Masculino',
    'Mz 12 Casa 5',
    '3107788990',
    'Mestizo',
    ARRAY[]::text[],
    'Casado',
    '2',
    'Pareja e hijos',
    3,
    2,
    3,
    8,
    'Apoyo social moderado',
    'Primaria',
    'no',
    'Conductor',
    'irregular',
    'no',
    null,
    'Junta vecinos',
    'no',
    ARRAY['hipertension']::text[],
    ARRAY['alcohol-ocasional']::text[],
    ARRAY['vias-en-mal-estado']::text[],
    ARRAY['deudas-creditos']::text[],
    ARRAY['proceso-juridico-transito']::text[],
    ARRAY['acceso-salud']::text[],
    ARRAY['empleo']::text[],
    ARRAY['seguridad-vial']::text[],
    ARRAY['asesoria-financiera']::text[],
    'Requiere apoyo para resolver multas de transito.',
    'Hector Valle',
    'Orientador',
    '3007701122',
    '[{"label":"Frustracion","intensity":0.8}]'::jsonb
  ),
  (
    '2025-02-05',
    '11:10:00',
    1005,
    'correo',
    'primer-contacto',
    'otro',
    'Kennedy',
    'Tintal',
    'si',
    null,
    null,
    null,
    'Angela Rios',
    '1999-01-15',
    'Femenino',
    'Calle 6 #86-41',
    '3185550099',
    'Afrodescendiente',
    ARRAY['juventud']::text[],
    'Soltera',
    '0',
    'Madre',
    1,
    1,
    2,
    4,
    'Bajo apoyo social',
    'Tecnologo',
    'si',
    'Estudiante',
    'buena',
    'si',
    'Ciclismo',
    'Semillero juvenil',
    'si',
    ARRAY[]::text[],
    ARRAY['consumo-cannabis']::text[],
    ARRAY['falta-iluminacion']::text[],
    ARRAY['falta-empleo']::text[],
    ARRAY[]::text[],
    ARRAY['orientacion-academica']::text[],
    ARRAY['becas']::text[],
    ARRAY['marketing-digital']::text[],
    ARRAY[]::text[],
    'Busca oportunidades para cursar maestria.',
    'Tania Cruz',
    'Tutora',
    '3049901122',
    '[{"label":"Motivacion","intensity":0.9}]'::jsonb
  ),
  (
    '2025-02-06',
    '13:05:00',
    1006,
    'en-persona',
    'seguimiento',
    'institucion',
    'Teusaquillo',
    'Park Way',
    'si',
    null,
    null,
    null,
    'Sergio Castaneda',
    '1975-07-29',
    'Masculino',
    'Av 28 #34-09',
    '3128899001',
    'Mestizo',
    ARRAY['persona-mayor']::text[],
    'Viudo',
    '2',
    'Con hijas',
    3,
    4,
    4,
    11,
    'Apoyo social moderado',
    'Profesional',
    'si',
    'Profesor',
    'buena',
    'no',
    null,
    'Comite pensionados',
    'si',
    ARRAY['cardiopatia']::text[],
    ARRAY[]::text[],
    ARRAY['aislamiento-social']::text[],
    ARRAY['presion-financiera']::text[],
    ARRAY[]::text[],
    ARRAY['acompanamiento-terapeutico']::text[],
    ARRAY['apoyo-economico']::text[],
    ARRAY['docencia']::text[],
    ARRAY['asesoria-juridica']::text[],
    'Necesita soporte para tramites pensionarios.',
    'Natalia Rueda',
    'Trabajadora social',
    '3102227788',
    '[{"label":"Tristeza","intensity":0.6}]'::jsonb
  ),
  (
    '2025-02-07',
    '16:25:00',
    1007,
    'telefono',
    'seguimiento',
    'otro',
    'Engativa',
    'Modelia',
    'no',
    'Paola Ortiz',
    'Sobrina',
    '3012223334',
    'Elena Duarte',
    '1987-04-23',
    'Femenino',
    'Diagonal 112 #75-05',
    '3134455566',
    'Mestizo',
    ARRAY['victima-violencia']::text[],
    'Separada',
    '1',
    'Con hermana',
    2,
    3,
    3,
    8,
    'Apoyo social moderado',
    'Secundaria',
    'no',
    'Manicurista',
    'regular',
    'no',
    null,
    'Grupo mujeres',
    'si',
    ARRAY['lesion-cronica']::text[],
    ARRAY[]::text[],
    ARRAY['movilidad-reducida']::text[],
    ARRAY['ventas-bajas']::text[],
    ARRAY['denuncia-pendiente']::text[],
    ARRAY['proteccion']::text[],
    ARRAY['microcreditos']::text[],
    ARRAY['estetica']::text[],
    ARRAY['asesoria-legal']::text[],
    'Solicita orientacion para independizarse.',
    'Laura Medina',
    'Psicologa',
    '3005551122',
    '[{"label":"Temor","intensity":0.7}]'::jsonb
  ),
  (
    '2025-02-08',
    '15:00:00',
    1008,
    'videollamada',
    'primer-contacto',
    'institucion',
    'Ciudad Bolivar',
    'Juan Jose Rondon',
    'si',
    null,
    null,
    null,
    'Jairo Benitez',
    '2000-12-01',
    'Masculino',
    'Calle 72A #18-55',
    '3190087766',
    'Afrodescendiente',
    ARRAY['juventud','lgbtiq']::text[],
    'Soltero',
    '0',
    'Familia extensa',
    4,
    4,
    5,
    13,
    'Alto apoyo social',
    'Tecnico',
    'si',
    'Tecnico de sonido',
    'buena',
    'si',
    'Baloncesto',
    'Colectivo cultural',
    'si',
    ARRAY[]::text[],
    ARRAY['bebidas-energeticas']::text[],
    ARRAY['falta-espacios-culturales']::text[],
    ARRAY['ingresos-inestables']::text[],
    ARRAY[]::text[],
    ARRAY['equipos-sonido']::text[],
    ARRAY['apoyo-emprendimiento']::text[],
    ARRAY['produccion-musical']::text[],
    ARRAY['asesoria-empresarial']::text[],
    'Quiere fortalecer colectivo musical barrial.',
    'Camilo Serrano',
    'Promotor cultural',
    '3149988776',
    '[{"label":"Entusiasmo","intensity":0.8}]'::jsonb
  ),
  (
    '2025-02-09',
    '09:40:00',
    1009,
    'en-persona',
    'seguimiento',
    'institucion',
    'Antonio Narino',
    'Restrepo',
    'si',
    null,
    null,
    null,
    'Patricia Mejia',
    '1970-05-19',
    'Femenino',
    'Carrera 20 #17-43',
    '3102223344',
    'Mestizo',
    ARRAY['persona-mayor']::text[],
    'Casada',
    '3',
    'Pareja',
    3,
    2,
    2,
    7,
    'Bajo apoyo social',
    'Primaria',
    'no',
    'Vendedora ambulante',
    'irregular',
    'no',
    null,
    'Parroquia',
    'si',
    ARRAY['artritis']::text[],
    ARRAY[]::text[],
    ARRAY['espacio-publico-inseguro']::text[],
    ARRAY['deudas']::text[],
    ARRAY[]::text[],
    ARRAY['apoyo-economico']::text[],
    ARRAY['alimentos']::text[],
    ARRAY['manualidades']::text[],
    ARRAY['asesoria-tributaria']::text[],
    'Requiere reorganizar deudas y encontrar apoyo social.',
    'Claudia Perez',
    'Trabajadora social',
    '3156677889',
    '[{"label":"Fatiga","intensity":0.6}]'::jsonb
  ),
  (
    '2025-02-10',
    '17:55:00',
    1010,
    'telefono',
    'cierre',
    'oficina',
    'Fontibon',
    'San Pablo',
    'no',
    'Luis Vega',
    'Amigo',
    '3111122334',
    'Rosa Herrera',
    '1993-08-30',
    'Femenino',
    'Diagonal 16 #110-03',
    '3012233445',
    'Mestizo',
    ARRAY['desplazado']::text[],
    'Union libre',
    '1',
    'Pareja',
    4,
    3,
    3,
    10,
    'Apoyo social moderado',
    'Secundaria',
    'si',
    'Auxiliar administrativa',
    'buena',
    'no',
    null,
    'Red desplazados',
    'si',
    ARRAY['migrañas']::text[],
    ARRAY[]::text[],
    ARRAY['transporte-inseguro']::text[],
    ARRAY['gastos-altos']::text[],
    ARRAY['restitucion-pendiente']::text[],
    ARRAY['vivienda']::text[],
    ARRAY['educacion-hijo']::text[],
    ARRAY['gestion-documental']::text[],
    ARRAY['asesoria-legal']::text[],
    'Proceso de cierre tras asignacion de subsidio de vivienda.',
    'Mateo Vargas',
    'Gestor social',
    '3186671122',
    '[{"label":"Alivio","intensity":0.9}]'::jsonb
  );
