INSERT INTO beneficiarios (
  caso_numero,
  fecha,
  hora,
  lugar_contacto,
  forma_contacto,
  tipo_contacto,
  localidad,
  barrio,
  mismo_beneficiario,
  fuente_nombre,
  fuente_vinculo,
  fuente_telefono,
  nombre_apellido,
  fecha_nacimiento,
  genero,
  direccion,
  telefono,
  grupo_etnico,
  estado_civil,
  convive_con,
  numero_hijos,
  apoyo_social_personas,
  apoyo_social_interes,
  apoyo_social_vecinos,
  apoyo_social_puntaje,
  apoyo_social_nivel,
  escolaridad,
  ocupacion,
  usa_computador,
  practica_deporte,
  cual_deporte,
  alimentacion,
  participacion_comunitaria,
  poblaciones_especiales,
  situaciones_salud,
  situaciones_consumo,
  situaciones_entorno,
  situaciones_economicas,
  situaciones_legales,
  peticiones_apoyo,
  peticiones_necesidades,
  peticiones_capacitacion,
  peticiones_asesoria,
  descripcion_caso,
  nombre_diligencia,
  rol_diligencia,
  telefono_diligencia,
  emociones
) VALUES

(
  '2',
  '2025-01-15',
  '10:30',
  'Centro Comunitario Kennedy',
  'Presencial',
  'Demanda espontánea',
  'Kennedy',
  'Patio Bonito',
  'Sí',
  NULL,
  NULL,
  NULL,
  'María Fernanda González Rodríguez',
  '1990-05-20',
  'Femenino',
  'Calle 38 Sur #78-45',
  '3201234567',
  'Ninguno',
  'Casada',
  'Pareja e hijos',
  '2',
  4,
  4,
  4,
  12,
  'Alto apoyo social',
  'Bachillerato completo',
  'Empleada',
  'Sí',
  'Sí',
  'Caminatas',
  'Buena',
  'Sí',
  '["Ninguna"]',
  '[]',
  '[]',
  '["Violencia intrafamiliar"]',
  '["Desempleo"]',
  '[]',
  '["Apoyo psicológico"]',
  '["Apoyo económico"]',
  '[]',
  '["Orientación jurídica"]',
  'Beneficiaria reporta situación de violencia intrafamiliar. Requiere apoyo psicológico urgente y orientación jurídica para proceso de separación. Tiene dos hijos menores que también necesitan acompañamiento.',
  'Carlos Méndez',
  'Trabajador Social',
  '3001234567',
  '[{"emocion":"Tristeza","intensidad":"moderada"},{"emocion":"Miedo","intensidad":"leve"}]'
),

(
  '3',
  '2025-01-16',
  '14:15',
  'Casa de Justicia Suba',
  'Presencial',
  'Remitido',
  'Suba',
  'Rincón',
  'Sí',
  NULL,
  NULL,
  NULL,
  'Juan Carlos Pérez Martínez',
  '1979-08-12',
  'Masculino',
  'Carrera 91 #145-23',
  '3159876543',
  'Ninguno',
  'Unión libre',
  'Pareja, hijo y madre',
  '1',
  3,
  3,
  2,
  8,
  'Apoyo social moderado',
  'Primaria completa',
  'Independiente',
  'No',
  'No',
  NULL,
  'Regular',
  'No',
  '[]',
  '["Hipertensión"]',
  '[]',
  '[]',
  '["Desempleo", "Bajos ingresos"]',
  '[]',
  '["Apoyo en salud"]',
  '["Apoyo económico"]',
  '["Orientación laboral"]',
  '[]',
  'Beneficiario en situación de desempleo desde hace 8 meses. Tiene problemas de hipertensión que requieren medicación constante. Vive con su compañera, un hijo menor y su madre adulta mayor. Busca apoyo para conseguir empleo y ayuda económica temporal.',
  'Ana Rodríguez',
  'Psicóloga',
  '3109876543',
  '[{"emocion":"Ansiedad","intensidad":"intensa"},{"emocion":"Tristeza","intensidad":"moderada"}]'
),

(
  '4',
  '2025-01-17',
  '09:00',
  'Centro de Atención Usme',
  'Presencial',
  'Demanda espontánea',
  'Usme',
  'Danubio',
  'Sí',
  NULL,
  NULL,
  NULL,
  'Luz Marina Torres Gómez',
  '1962-03-15',
  'Femenino',
  'Diagonal 56 Sur #15-67',
  '3187654321',
  'Ninguno',
  'Viuda',
  'Esposo',
  '0',
  2,
  2,
  3,
  7,
  'Bajo apoyo social',
  'Sin escolaridad',
  'Pensionada',
  'No',
  'No',
  NULL,
  'Regular',
  'No',
  '["Adulto mayor", "Persona con discapacidad en el hogar"]',
  '["Diabetes", "Artritis"]',
  '[]',
  '[]',
  '["Bajos ingresos"]',
  '[]',
  '["Apoyo en salud", "Acompañamiento social"]',
  '["Apoyo económico"]',
  '[]',
  '[]',
  'Adulta mayor en situación de vulnerabilidad. Vive con su esposo quien también es adulto mayor y tiene discapacidad. Requiere apoyo para acceso a medicamentos y acompañamiento social. Pensión mínima no alcanza para cubrir gastos médicos.',
  'Patricia Sánchez',
  'Enfermera',
  '3156789012',
  '[{"emocion":"Tristeza","intensidad":"intensa"},{"emocion":"Soledad","intensidad":"moderada"}]'
),

(
  '5',
  '2025-01-18',
  '11:45',
  'Comisaría de Familia Engativá',
  'Presencial',
  'Remitido',
  'Engativá',
  'Minuto de Dios',
  'No',
  'Madre del beneficiario',
  'Madre',
  '3145678900',
  'Andrés Felipe Morales Castro',
  '2005-11-08',
  'Masculino',
  'Calle 80 #98-34',
  '3145678901',
  'Ninguno',
  'Soltero',
  'Padres y hermanos',
  '0',
  3,
  3,
  3,
  9,
  'Apoyo social moderado',
  'Bachillerato incompleto',
  'Desempleado',
  'Sí',
  'Sí',
  'Fútbol',
  'Regular',
  'Sí',
  '[]',
  '[]',
  '["Consumo de sustancias psicoactivas"]',
  '["Conflictos familiares"]',
  '["Desempleo"]',
  '[]',
  '["Apoyo psicológico", "Tratamiento adicciones"]',
  '[]',
  '["Apoyo educativo", "Orientación laboral"]',
  '[]',
  'Joven en situación de consumo de sustancias psicoactivas. Desertó del colegio en grado 10. Conflictos familiares constantes. Muestra interés en retomar estudios y conseguir empleo. Requiere tratamiento para adicciones y apoyo psicológico.',
  'Diego Ramírez',
  'Trabajador Social',
  '3178901234',
  '[{"emocion":"Ira","intensidad":"moderada"},{"emocion":"Confusión","intensidad":"intensa"}]'
),

(
  '6',
  '2025-01-19',
  '15:30',
  'Centro Comunitario Bosa',
  'Presencial',
  'Demanda espontánea',
  'Bosa',
  'El Porvenir',
  'Sí',
  NULL,
  NULL,
  NULL,
  'Carmen Rosa Díaz Hernández',
  '1996-07-25',
  'Femenino',
  'Carrera 78C #57-89 Sur',
  '3112345678',
  'Ninguno',
  'Madre soltera',
  'Hijos',
  '2',
  4,
  4,
  4,
  12,
  'Alto apoyo social',
  'Técnico',
  'Empleada',
  'Sí',
  'Sí',
  'Bailar',
  'Buena',
  'Sí',
  '["Madre cabeza de familia"]',
  '[]',
  '[]',
  '[]',
  '["Bajos ingresos"]',
  '[]',
  '["Apoyo en cuidado infantil"]',
  '["Apoyo económico"]',
  '[]',
  '["Orientación jurídica"]',
  'Madre cabeza de familia con dos hijos menores de 5 años. Trabaja como auxiliar de enfermería pero el salario no alcanza para cubrir todas las necesidades. Requiere apoyo con cuidado infantil para poder trabajar tiempo completo. Busca mejorar condiciones de vivienda.',
  'Laura Martínez',
  'Trabajadora Social',
  '3123456789',
  '[{"emocion":"Esperanza","intensidad":"moderada"},{"emocion":"Ansiedad","intensidad":"leve"}]'
);
